---
# -- wil-playgroud -- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playgroud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playgroud
  template:
    metadata:
      labels:
        app: wil-playgroud
    spec:
      containers:
      - name: wil-playgroud
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-playgroud
spec:
  selector:
    app: wil-playgroud
  ports:
  - port: 80
    targetPort: 8888
---
# -- Ingress -- #
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
  - host: 
    http:
      paths:
      - backend:
          service:
            name: wil-playgroud
            port: 
              number: 80
        path: "/"
        pathType: Prefix
